export const cities = [
  { country: "Chile", city: "Santiago" },
  { country: "Chile", city: "Valparaíso" },
  { country: "Chile", city: "Concepción" },
  { country: "Chile", city: "Temuco" },
  { country: "Chile", city: "Valdivia" },
  { country: "Chile", city: "Antofagasta" },
  { country: "Argentina", city: "Buenos Aires" },
  { country: "Argentina", city: "Córdoba" },
  { country: "Argentina", city: "Rosario" },
  { country: "Perú", city: "Lima" },
  { country: "Perú", city: "Cusco" },
  { country: "Uruguay", city: "Montevideo" },
  { country: "Brasil", city: "São Paulo" },
  { country: "Brasil", city: "Rio de Janeiro" },
  { country: "México", city: "Ciudad de México" },
  { country: "México", city: "Guadalajara" },
  { country: "Colombia", city: "Bogotá" },
  { country: "Colombia", city: "Medellín" },
  { country: "Ecuador", city: "Quito" },
  { country: "Bolivia", city: "La Paz" },
];
