// This file is automatically generated by Monicon. Do not edit this file directly.
import "@monicon/icon-loader";

declare module "@monicon/icon-loader" {
  export type MoniconIconName = 
	| "fluent-mdl2:lock"
	| "fluent-mdl2:view"
	| "hugeicons:student"
	| "mdi:school"
	| "mdi-light:eye-off"
	| "feather:activity"
	| "logos:active-campaign"
	| "mdi:home-outline"
	| "feather:search"
	| "mdi:calendar"
	| "fluent:alert-20-regular"
	| "mdi:account-circle-outline"
	| "mdi:cog"
	| "mdi:arrow-left"
	| "mdi:translate-variant"
	| "mdi:shield-check"
	| "mdi:help-circle";

  export type MoniconProps = {
    /**
     * The name of the icon to render.
     *
     * @example "mdi:home"
     *
     * For TypeScript users, you must check below for more information.
     *
     * @link https://monicon-docs.vercel.app/troubleshooting/typescript
     */
    name: MoniconIconName;
    /**
     * The size of the icon.
     *
     * @default collection's view box size
     */
    size?: number;
    /**
     * The color of the icon.
     *
     * @default "currentColor"
     */
    color?: string;
    /**
     * The stroke width of the icon. This feature is only available for limited icon collections.
     */
    strokeWidth?: number;
  };
}
